# Dependencies
highlighter:      rouge

# Setup
title:            Zoran Radovanovic
tagline:          'A Jekyll theme'
description:      'This web site is presentation of my professional biography and a blog about things I like doing professionally and in my spare time.'
url:
baseurl:          /

author:
  name:           'Zoran Radovanovic'
  url:            https://twitter.com/cybervando

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ranzer
